# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - itovsbasement

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_fb597f00eed043648b9677507c18da19 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8e7f5f6c8bfa489fb16e0152ed9c6075 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fb597f00eed043648b9677507c18da19 }}/pbering/itovsbasement-website:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'itovsbasement'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_c83ff769f0bb4c339730dd30507a11c2 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fb597f00eed043648b9677507c18da19 }}/pbering/itovsbasement-website:${{ github.sha }}'